Repository dusk-network/dusk-blockchain, pull requests merged in 2019-12, with the labels that each got.

#164 Only double reduction timers on failure to converge on a value
  pkg/core/consensus/reduction/firststep/reducer.go
  pkg/core/consensus/reduction/firststep/reduction_test.go
  pkg/core/consensus/reduction/secondstep/reducer.go
  pkg/core/consensus/reduction/secondstep/reduction_test.go
Labels: Node:Consensus

#161 Remove CLI package in favor of RPC endpoints
  harness/engine/utils.go
  launch/testnet/main.go
  pkg/cli/cli.go
  pkg/cli/commands.go
  pkg/cli/info.go
  pkg/cli/walletcommands.go
  pkg/rpc/README.md
  pkg/rpc/commands.go
  pkg/rpc/handler.go
Labels: Network:Infrastructure, Node:Clients, enhancement

#182 Protocol methods refactoring.
  pkg/p2p/kadcast/packet.go
  pkg/p2p/kadcast/peer.go
  pkg/p2p/kadcast/protocol.go
  pkg/p2p/kadcast/router.go
  pkg/p2p/kadcast/utils.go
Labels: Architecture, enhancement

#141 Kadcast functional implementation
  cmd/main.go
  go.mod
  go.sum
  pkg/p2p/kadcast/bucket.go
  pkg/p2p/kadcast/network.go
  pkg/p2p/kadcast/packet.go
  pkg/p2p/kadcast/peer.go
  pkg/p2p/kadcast/protocol.go
  pkg/p2p/kadcast/router.go
  pkg/p2p/kadcast/tree.go
  pkg/p2p/kadcast/utils.go
  pkg/p2p/kadcast/utils_test.go
Labels: Network:Communication, Network:Infrastructure, discussion, enhancement

#177 Queue agreement events on a seperate queue which flushes on a round update
  pkg/core/consensus/round.go
  pkg/core/consensus/round_test.go
Labels: Node:Consensus, bug

#174 Substitute Ed25519 message signing and verification for Blake2b checksums
  pkg/core/chain/candidate/blockgenerator.go
  pkg/core/chain/candidate/testutil.go
  pkg/core/chain/chain.go
  pkg/core/consensus/agreement/agreement.go
  pkg/core/consensus/component.go
  pkg/core/consensus/eventprocessor.go
  pkg/core/consensus/eventprocessor_test.go
  pkg/core/consensus/generation/generator.go
  pkg/core/consensus/generation/score/generator.go
  pkg/core/consensus/msg/validation.go
  pkg/core/consensus/readme.md
  pkg/core/consensus/reduction/firststep/reducer.go
  pkg/core/consensus/reduction/reduction_test.go
  pkg/core/consensus/reduction/secondstep/reducer.go
  pkg/core/consensus/reduction/testutil.go
  pkg/core/consensus/round.go
  pkg/core/consensus/selection/selector.go
  pkg/core/consensus/selection/testutil.go
  pkg/p2p/peer/handshake.go
  pkg/p2p/peer/peer.go
  pkg/p2p/peer/peer_test.go
  pkg/p2p/peer/processing/frame.go
  pkg/p2p/peer/processing/frame_test.go
  pkg/p2p/peer/processing/gossip.go
  pkg/p2p/peer/processing/gossip_test.go
  pkg/p2p/wire/checksum/checksum.go
  pkg/p2p/wire/checksum/checksum_test.go
  pkg/util/nativeutils/eventbus/eventbus_test.go
  pkg/util/nativeutils/eventbus/mock.go
Labels: Network:Communication, enhancement

#199 Add/implement RPC commands
  pkg/core/transactor/listener.go
  pkg/core/transactor/transactor.go
  pkg/rpc/README.md
  pkg/rpc/commands.go
  pkg/util/nativeutils/rpcbus/methods.go
Labels: Node:Clients, enhancement

#205 Minor updates to the RPC server
  go.mod
  go.sum
  harness/engine/utils.go
  harness/tests/localnet_test.go
  pkg/config/samples/default.dusk.toml
  pkg/core/consensus/maintainer/maintainer_test.go
  pkg/core/transactor/listener.go
  pkg/core/transactor/transactor.go
  pkg/rpc/README.md
  pkg/rpc/commands.go
  pkg/rpc/handler.go
  pkg/util/nativeutils/rpcbus/methods.go
Labels: Network:Infrastructure, Node:Clients, enhancement

#206 Add a bash script, and an executable, for launching both the blind bid and the node at the same time
  README.md
  launch/start-node/README.md
  launch/start-node/start-node.go
  launch/testnet/start-node.sh
Labels: enhancement

#212 Add a JSON-RPC command to inquire whether or not the wallet is loaded
  pkg/core/transactor/listener.go
  pkg/core/transactor/transactor.go
  pkg/rpc/commands.go
  pkg/util/nativeutils/rpcbus/methods.go
Labels: enhancement

#213 Add support for fetching synchronization progress as a percentage
  pkg/core/chain/chain.go
  pkg/core/chain/collectors.go
  pkg/p2p/peer/processing/chainsync/sync.go
  pkg/p2p/peer/processing/chainsync/sync_test.go
  pkg/p2p/wire/topics/topics.go
  pkg/rpc/commands.go
  pkg/util/nativeutils/rpcbus/methods.go
Labels: Node:Blockchain, enhancement

#214 Update README.md
  README.md
Labels: documentation

#211 Make maintainer launch optional instead of mandatory
  README.md
  pkg/config/groups.go
  pkg/config/loader.go
  pkg/config/samples/default.dusk.toml
  pkg/core/consensus/initiator/initiator.go
  pkg/core/consensus/maintainer/maintainer.go
  pkg/core/consensus/maintainer/maintainer_test.go
  pkg/core/transactor/listener.go
  pkg/core/transactor/transactor.go
  pkg/rpc/commands.go
  pkg/util/nativeutils/rpcbus/methods.go
Labels: enhancement

#217 Fix sync percentage, update dusk-wallet import
  go.mod
  go.sum
  pkg/core/chain/chain.go
Labels: minor

#218 Small fixes to bugs found during final tests
  pkg/core/consensus/maintainer/maintainer.go
  pkg/core/transactor/listener.go
  pkg/p2p/peer/router.go
Labels: Network:Communication, bug

#221 Complete JSON-RPC documentation
  pkg/rpc/README.md
Labels: documentation, enhancement
