Repository dusk-network/dusk-blockchain, pull requests merged in 2020-01, with the labels that each got.

#234 Add length check when decoding data of variable size
  pkg/core/consensus/agreement/event.go
  pkg/core/marshalling/block.go
  pkg/core/marshalling/transactions.go
  pkg/p2p/peer/peermsg/getblocks.go
  pkg/p2p/wire/encoding/vardata.go
Labels: Network:Communication, vulnerability

#232 Remove Preprocessor logic in preparation of EventBus modularization
  Makefile
  launch/testnet/server.go
  pkg/core/candidate/broker.go
  pkg/core/candidate/collector.go
  pkg/core/candidate/store_test.go
  pkg/core/candidate/validator.go
  pkg/core/candidate/validator_test.go
  pkg/core/chain/chain_test.go
  pkg/core/consensus/agreement/agreement.go
  pkg/core/consensus/agreement/agreement_test.go
  pkg/core/consensus/agreement/factory.go
  pkg/core/consensus/component.go
  pkg/core/consensus/reduction/firststep/factory.go
  pkg/core/consensus/reduction/firststep/reducer.go
  pkg/core/consensus/reduction/reduction_test.go
  pkg/core/consensus/round.go
  pkg/p2p/peer/peer.go
  pkg/p2p/peer/peer_test.go
  pkg/p2p/peer/processing/gossip.go
  pkg/util/nativeutils/eventbus/eventbus.go
  pkg/util/nativeutils/eventbus/eventbus_test.go
  pkg/util/nativeutils/eventbus/mock.go
  pkg/util/nativeutils/eventbus/preprocessor.go
  pkg/util/nativeutils/eventbus/publisher.go
  pkg/util/nativeutils/republisher/republisher.go
  pkg/util/nativeutils/republisher/republisher_test.go
Labels: Architecture

#222 Update to dusk-wallet v1.1.3
  go.mod
  go.sum
Labels: enhancement

#229 Enforce an item limit on inv messages
  pkg/config/loader.go
  pkg/core/mempool/mempool_test.go
  pkg/p2p/peer/peermsg/inventory.go
  pkg/p2p/peer/peermsg/inventory_test.go
Labels: Network:Communication, bug, vulnerability

#235 Replace all relevant calls to panic with log.Panic
  launch/testnet/cmgr.go
  launch/testnet/main.go
  launch/testnet/seeder.go
  launch/testnet/server.go
  pkg/config/consts.go
  pkg/core/chain/chain.go
  pkg/core/consensus/generation/score/generator.go
  pkg/core/consensus/initiator/initiator.go
  pkg/core/consensus/round.go
  pkg/core/consensus/state.go
  pkg/core/consensus/user/sortition.go
  pkg/core/database/heavy/driver.go
  pkg/core/database/heavy/transactions.go
  pkg/core/database/lite/driver.go
  pkg/core/mempool/mempool.go
  pkg/p2p/peer/processing/chainsync/sync.go
  pkg/p2p/peer/responding/datarequestor.go
  pkg/p2p/wire/protocol/protocol.go
Labels: enhancement

#227 Ensure coinbase on first intermediate block is deterministic
  pkg/core/chain/chain.go
  pkg/core/consensus/candidate/blockgenerator.go
  pkg/core/verifiers/transaction.go
Labels: Node:Blockchain, Node:Consensus, bug

#236 Ensure candidate blocks are only stored after a valid Score message is seen
  pkg/core/candidate/broker.go
  pkg/core/candidate/broker_test.go
  pkg/core/consensus/selection/selector.go
  pkg/p2p/wire/topics/topics.go
Labels: Node:Consensus, vulnerability

#240 remove topic collector from the mempool
  pkg/core/candidate/collector.go
  pkg/core/chain/collectors.go
  pkg/core/consensus/collector.go
  pkg/core/consensus/eventnotification.go
  pkg/core/mempool/collector.go
  pkg/core/mempool/mempool.go
  pkg/eventmon/logger/logger.go
  pkg/util/nativeutils/eventbus/collector.go
  pkg/util/nativeutils/eventbus/eventbus_test.go
Labels: Architecture

#242 Add functionality for getting a view of the mempool, with certain filters
  pkg/core/mempool/hashmap.go
  pkg/core/mempool/hashmap_test.go
  pkg/core/mempool/interface.go
  pkg/core/mempool/mempool.go
  pkg/core/mempool/mempool_test.go
  pkg/rpc/README.md
  pkg/rpc/commands.go
  pkg/util/nativeutils/rpcbus/methods.go
Labels: enhancement

#249 Default log level to debug
  pkg/config/loader_test.go
  pkg/config/samples/default.dusk.toml
Labels: enhancement

#245 Look up tx by key when requested through `GetMempoolTxs`
  pkg/core/mempool/mempool.go
Labels: enhancement

#252 Modularise RPC server
  launch/testnet/server.go
  pkg/rpc/commands.go
  pkg/rpc/handler.go
  pkg/rpc/rpcserver.go
Labels: Node:Clients, enhancement

#258 Avoid range-loop based panic in sortition
  pkg/core/consensus/user/sortition.go
  pkg/core/consensus/user/sortition_test.go
Labels: Node:Consensus, bug

#241 Complete unimplented functions in the lite database
  pkg/core/database/heavy/transactions.go
  pkg/core/database/lite/database.go
  pkg/core/database/lite/transactions.go
  pkg/core/database/testing/drivers_test.go
Labels: Testing, enhancement

#246 Add functionality for rebuilding the chain
  go.mod
  go.sum
  pkg/core/chain/chain.go
  pkg/core/chain/chain_test.go
  pkg/core/database/heavy/transactions.go
  pkg/core/database/interfaces.go
  pkg/core/database/lite/transactions.go
  pkg/core/database/testing/drivers_test.go
  pkg/core/transactor/listener.go
  pkg/core/transactor/transactor.go
  pkg/rpc/README.md
  pkg/rpc/commands.go
  pkg/util/nativeutils/rpcbus/methods.go
Labels: Node:Blockchain, enhancement
