Repository dusk-network/dusk-blockchain, pull requests merged in 2020-04, with the labels that each got.

#194 Build skeleton for TCP broadcast network.
  cmd/kadcast/main.go
  pkg/p2p/kadcast/bucket.go
  pkg/p2p/kadcast/network.go
  pkg/p2p/kadcast/packet.go
  pkg/p2p/kadcast/packet_processor.go
  pkg/p2p/kadcast/router.go
  pkg/p2p/kadcast/utils.go
Labels: Network:Communication, Network:Infrastructure, enhancement

#371 Grpc monitor
  cmd/dusk/monitor.go
  cmd/dusk/server.go
  go.mod
  go.sum
  harness/README.md
  pkg/config/groups.go
  pkg/config/samples/default.dusk.toml
  pkg/eventmon/grpc/client.go
  pkg/eventmon/grpc/client_test.go
  pkg/eventmon/grpc/error.go
  pkg/eventmon/grpc/hello.go
  pkg/eventmon/grpc/hello_test.go
  pkg/eventmon/grpc/round.go
  pkg/eventmon/grpc/round_test.go
  pkg/eventmon/grpc/supervisor.go
  pkg/eventmon/grpc/supervisor_test.go
  pkg/eventmon/monitor/monitor.go
  pkg/p2p/wire/topics/topics.go
  pkg/rpc/server.go
  pkg/util/nativeutils/eventbus/publisher.go
Labels: Network:Infrastructure

#391 add test-harness to travis ci #368
  .travis.yml
  Makefile
  cmd/dusk/monitor.go
  cmd/dusk/server.go
  go.mod
  go.sum
  harness/tests/localnet_test.go
  pkg/rpc/client.go
Labels: Node:Blockchain, Testing, enhancement

#402 Lint fails from time to time with errs on pkg/p2p/peer/peer_test.go and p2p/peer/handshake_test.go #401
  Makefile
  pkg/core/tests/helper/util.go
  pkg/p2p/peer/handshake_test.go
  pkg/p2p/peer/peer_test.go
  pkg/p2p/peer/peer_test_func.go
Labels: Node:Blockchain, Testing, bug

#414 Migrate dusk-wallet-cli to be a command within dusk-blockchain #410
  Makefile
  cmd/dusk/action.go
  cmd/dusk/voucher.go
  cmd/wallet/conf/client.go
  cmd/wallet/conf/config.go
  cmd/wallet/main.go
  cmd/wallet/prompt/loading.go
  cmd/wallet/prompt/prompt.go
  cmd/wallet/prompt/transfer.go
  go.mod
  go.sum
  scripts/build.go
Labels: enhancement, node-wallet

#408 enable cross compiling of dusk-blochain cmds #390
  Makefile
  go.mod
  go.sum
  pkg/core/database/heavy/transactions.go
Labels: enhancement

#419 Remove Twisted Edward signature from the Stake transaction
  cmd/dusk/server.go
  pkg/config/consts.go
  pkg/core/candidate/store_test.go
  pkg/core/chain/chain.go
  pkg/core/chain/chain_test.go
  pkg/core/chain/loader.go
  pkg/core/chain/mock.go
  pkg/core/consensus/candidate/genesis_test.go
  pkg/core/consensus/key/keys.go
  pkg/core/consensus/key/keys_test.go
  pkg/core/consensus/maintainer/maintainer_test.go
  pkg/core/consensus/mock.go
  pkg/core/consensus/user/provisioners.go
  pkg/core/consensus/user/sortition.go
  pkg/core/data/database/database_test.go
  pkg/core/data/transactions/staketx.go
  pkg/core/data/wallet/transactions.go
  pkg/core/data/wallet/wallet_test.go
  pkg/core/tests/helper/block.go
  pkg/core/tests/helper/transactions.go
  pkg/core/verifiers/block.go
  pkg/p2p/wire/message/block.go
  pkg/p2p/wire/message/block_test.go
  pkg/p2p/wire/message/transactions.go
Labels: enhancement

#423 Modularize the gRPC server to separate components
  .travis.yml
  cmd/dusk/server.go
  cmd/wallet/conf/client.go
  cmd/wallet/main.go
  cmd/wallet/prompt/loading.go
  cmd/wallet/prompt/prompt.go
  cmd/wallet/prompt/transfer.go
  go.mod
  go.sum
  harness/engine/utils.go
  pkg/core/chain/chain.go
  pkg/core/chain/chain_test.go
  pkg/core/consensus/maintainer/maintainer.go
  pkg/core/consensus/maintainer/maintainer_test.go
  pkg/core/mempool/mempool.go
  pkg/core/mempool/mempool_test.go
  pkg/core/transactor/commands.go
  pkg/core/transactor/listener.go
  pkg/core/transactor/transactor.go
  pkg/core/transactor/utils.go
  pkg/rpc/client.go
  pkg/rpc/example_test.go
  pkg/rpc/server.go
  scripts/build.go
Labels: area:IPC, area:tx
