Repository dusk-network/dusk-blockchain, pull requests merged in 2020-05, with the labels that each got.

#465 Reinstate the consensus initiator
  pkg/core/consensus/candidate/factory.go
  pkg/core/consensus/candidate/testutil.go
  pkg/core/consensus/factory/factory.go
  pkg/core/consensus/initiator/initiator.go
  pkg/core/transactor/listener.go
Labels: area:IPC, type:rfc, type:tech-debt

#490 Provide the block generator with the latest winning committee
  pkg/core/chain/chain.go
  pkg/core/chain/chain_test.go
  pkg/core/chain/collectors.go
  pkg/core/consensus/agreement/agreement.go
  pkg/core/consensus/agreement/agreement_in_test.go
  pkg/core/consensus/agreement/agreement_test.go
  pkg/core/consensus/agreement/handler.go
  pkg/core/consensus/agreement/handler_test.go
  pkg/core/consensus/candidate/blockgenerator.go
  pkg/core/consensus/candidate/genesis.go
  pkg/p2p/wire/message/certificate.go
  pkg/p2p/wire/topics/topics.go
Labels: area:block-generation, area:tx, type:feature

#491 Save/Retrieve PublicKey and ViewKey from .dat file in the Wallet#471
  pkg/config/groups.go
  pkg/core/data/transactions/provider.go
  pkg/core/data/wallet/wallet.go
  pkg/core/data/wallet/wallet_test.go
  pkg/core/transactor/funcs.go
  pkg/core/transactor/listener.go
Labels: area:IPC, area:wallet, type:refactor

#511 Remove bid
  pkg/core/consensus/user/bidlist.go
Labels: area:block-generation, type:rfc

#513 Rework GQL functionality and tests to be compatible with phoenix transactions
  pkg/core/data/transactions/fixtures.go
  pkg/core/tests/helper/transactions.go
  pkg/gql/query/blocks_test.go
  pkg/gql/query/query_test.go
  pkg/gql/query/transactions.go
  pkg/gql/query/transactions_test.go
Labels: area:IPC, area:tx, type:tech-debt

#505 Fix maintainer, split automaton into two
  cmd/dusk/server.go
  go.mod
  go.sum
  pkg/config/consts.go
  pkg/core/consensus/bidautomaton/bidautomaton.go
  pkg/core/consensus/bidautomaton/bidautomaton_test.go
  pkg/core/consensus/maintainer/maintainer.go
  pkg/core/consensus/maintainer/maintainer_test.go
  pkg/core/consensus/stakeautomaton/stakeautomaton.go
  pkg/core/consensus/stakeautomaton/stakeautomaton_test.go
  pkg/core/transactor/listener.go
  pkg/core/transactor/transactor.go
  pkg/util/nativeutils/rpcbus/rpcbus.go
Labels: area:IPC, area:tx, type:tech-debt

#520 Create keys when creating wallet
  pkg/core/transactor/funcs.go
Labels: area:wallet, type:rfc

#522 Create a wallet from the given seed, when calling CreateFromSeed
  cmd/dusk/server.go
  pkg/core/transactor/funcs.go
  pkg/core/transactor/listener.go
  pkg/core/transactor/transactor.go
Labels: area:wallet, type:rfc

#514 Regenerate genesis block, and fix related tests
  pkg/config/consts.go
  pkg/core/chain/chain_test.go
  pkg/core/consensus/candidate/blockgenerator.go
  pkg/core/consensus/candidate/factory.go
  pkg/core/consensus/candidate/generation_test.go
  pkg/core/consensus/candidate/genesis.go
  pkg/core/consensus/candidate/genesis_test.go
  pkg/core/consensus/candidate/testutil.go
  pkg/core/consensus/factory/factory.go
  pkg/core/consensus/initiator/initiator.go
  pkg/core/data/transactions/distribute.go
  pkg/core/data/transactions/fixtures.go
  pkg/core/database/testing/drivers_test.go
  pkg/core/tests/helper/block.go
Labels: area:block-generation, area:block-validation, area:conf&build, area:testing, type:refactor, type:tech-debt

#515 Update wallet CLI to conform to latest node updates
  cmd/wallet/conf/client.go
  cmd/wallet/prompt/prompt.go
Labels: area:IPC, area:wallet, type:tech-debt

#527 Allow multithreading during unit tests
  .travis.yml
  Makefile
Labels: area:testing

#533 Implement GetUnconfirmedBalance
  cmd/dusk/server.go
  go.mod
  go.sum
  pkg/core/consensus/candidate/generation_test.go
  pkg/core/data/transactions/fixtures.go
  pkg/core/data/transactions/provider.go
  pkg/core/mempool/mempool.go
  pkg/core/mempool/mempool_test.go
Labels: area:IPC, area:tx, type:feature, type:tech-debt

#546 Add metrics exporter cmd to expose Dusk blockchain metrics - #528
  Makefile
  cmd/utils/main.go
  cmd/utils/metrics/api.go
  cmd/utils/metrics/metrics.go
  cmd/utils/metrics/model.go
  cmd/utils/metrics/rpc.go
Labels: area:IPC, type:feature

#536 Add a mock Rusk server, which can be used for testing
  .travis.yml
  Makefile
  cmd/dusk/server.go
  go.mod
  go.sum
  harness/README.md
  harness/data/wallet-9000.dat
  harness/data/wallet-9001.dat
  harness/data/wallet-9002.dat
  harness/data/wallet-9003.dat
  harness/data/wallet-9004.dat
  harness/data/wallet-9005.dat
  harness/data/wallet-9006.dat
  harness/data/wallet-9007.dat
  harness/data/wallet-9008.dat
  harness/data/wallet-9009.dat
  harness/engine/network.go
  harness/engine/node.go
  harness/engine/profiles.go
  harness/engine/utils.go
  harness/tests/localnet_test.go
  pkg/config/consts.go
  pkg/config/groups.go
  pkg/config/loader.go
  pkg/config/samples/default.dusk.toml
  pkg/core/chain/chain.go
  pkg/core/chain/legacy.go
  pkg/core/consensus/generation/score/generator.go
  pkg/core/consensus/initiator/initiator.go
  pkg/core/consensus/user/provisioners.go
  pkg/core/data/transactions/distribute.go
  pkg/core/data/transactions/fixtures.go
  pkg/core/data/transactions/provider.go
  pkg/core/transactor/funcs.go
  pkg/core/transactor/listener.go
  pkg/core/transactor/transactor.go
  pkg/util/legacy/conversions.go
  pkg/util/legacy/genesis.go
  pkg/util/legacy/marshalling.go
  pkg/util/ruskmock/server.go
Labels: area:IPC, area:testing, area:tx, type:feature
