Repository dusk-network/dusk-blockchain, pull requests merged in 2020-07, with the labels that each got.

#581 add devnet.sh support for master branch, upgrade lint and test consensus with multiple bidders #580
  Makefile
  cmd/utils/main.go
  cmd/utils/walletutils/wallet.go
  devnet.sh
  go.mod
  harness/tests/localnet_test.go
  pkg/core/data/wallet/seed.go
  pkg/p2p/kadcast/packet.go
  scripts/build.go
Labels: area:testing, type:feature

#597 Initialize the input being decoded in ruskInputsToInputs
  pkg/util/legacy/conversions.go
Labels: area:IPC, area:testing, type:bug

#601 Initialize Signature struct before decoding it
  pkg/util/legacy/conversions.go
Labels: area:testing, area:tx, type:bug

#602 Synchronize access to the 'Halt' method
  pkg/core/consensus/reduction/firststep/aggregator.go
  pkg/core/consensus/reduction/firststep/aggregator_test.go
  pkg/core/consensus/reduction/firststep/reducer.go
  pkg/core/consensus/reduction/firststep/reduction_test.go
  pkg/core/consensus/reduction/firststep/testutil.go
  pkg/core/consensus/reduction/reducer.go
  pkg/core/consensus/reduction/reduction_test.go
  pkg/core/consensus/reduction/secondstep/aggregator.go
  pkg/core/consensus/reduction/secondstep/aggregator_test.go
  pkg/core/consensus/reduction/secondstep/reducer.go
  pkg/core/consensus/reduction/secondstep/reduction_test.go
  pkg/core/consensus/reduction/timer.go
  pkg/core/consensus/reduction/timer_test.go
Labels: area:testing, type:bug
