Repository dusk-network/dusk-blockchain, pull requests merged in 2021-06, with the labels that each got.

#1061 Use a ticker, instead of time.After, for mempool idling
  pkg/core/mempool/mempool.go
Labels: area:tx, team:WebTech, type:rfc

#1063 Clean up timer resources properly when using RPCBus
  pkg/util/nativeutils/rpcbus/rpcbus.go
Labels: team:WebTech, type:rfc

#1057 Optimize broadcast implementation in kadcast
  pkg/p2p/kadcast/encoding/header.go
  pkg/p2p/kadcast/maintainer.go
  pkg/p2p/kadcast/network_test.go
  pkg/p2p/kadcast/udpreader.go
  pkg/p2p/kadcast/utils.go
  pkg/p2p/kadcast/utils_test.go
  pkg/p2p/kadcast/writer.go
  pkg/util/nativeutils/rcudp/packet.go
  pkg/util/nativeutils/rcudp/packet_test.go
  pkg/util/nativeutils/rcudp/reader.go
  pkg/util/nativeutils/rcudp/writer.go
Labels: team:WebTech

#1065 Ensure queues are cleaned up properly after each round
  pkg/core/consensus/queue.go
  pkg/core/loop/consensus.go
  pkg/core/loop/consensus_test.go
Labels: team:WebTech, type:bug, type:rfc

#1067 Integrate Height byte field into UDP packet
  pkg/p2p/kadcast/basereader.go
  pkg/p2p/kadcast/tcpreader.go
  pkg/p2p/kadcast/writer.go
  pkg/util/nativeutils/rcudp/config.go
  pkg/util/nativeutils/rcudp/packet.go
  pkg/util/nativeutils/rcudp/packet_test.go
  pkg/util/nativeutils/rcudp/reader.go
  pkg/util/nativeutils/rcudp/writer.go
Labels: team:WebTech

#1077 Reduce frequency at which the StormDB is called
  pkg/p2p/peer/connector.go
  pkg/p2p/peer/peer.go
Labels: team:WebTech, type:bug, type:refactor

#1072 Use ringbuffer directly in favor of respChan
  cmd/voucher/challenger/challenger.go
  pkg/core/candidate/requestor_test.go
  pkg/core/chain/chain_test.go
  pkg/core/consensus/reduction/testutil.go
  pkg/p2p/peer/connector.go
  pkg/p2p/peer/factory.go
  pkg/p2p/peer/handshake_test.go
  pkg/p2p/peer/peer.go
  pkg/p2p/peer/peer_in_test.go
  pkg/p2p/peer/peer_test.go
  pkg/p2p/peer/processor.go
Labels: area:p2p, team:WebTech, type:bug

#1081 Fix devnet.sh #1079
  devnet.sh
Labels: team:WebTech

#1083 Set version tag to 0.4.3
  pkg/p2p/wire/protocol/protocol.go
Labels: team:WebTech

#1086 Extend ring buffer and Kadcast Writer
  go.mod
  go.sum
  pkg/p2p/kadcast/writer.go
  pkg/p2p/peer/peer.go
  pkg/p2p/peer/processor.go
  pkg/util/container/ring/buffer.go
  pkg/util/container/ring/buffer_test.go
  pkg/util/container/ring/consumer.go
  pkg/util/nativeutils/eventbus/eventbus_test.go
  pkg/util/nativeutils/eventbus/listener.go
  pkg/util/nativeutils/eventbus/mock.go
Labels: team:WebTech

#1098 Extend contract timeout to account for potential hangs
  devnet.sh
  harness/engine/node.go
  harness/engine/profiles.go
  pkg/config/samples/default.dusk.toml
Labels: area:IPC, team:WebTech, type:bug

#1096 Remove APK and step from Agreement message
  pkg/core/consensus/agreement/accumulator.go
  pkg/core/consensus/reduction/aggregator.go
  pkg/core/consensus/reduction/secondstep/reduction_test.go
  pkg/core/data/ipc/transactions/fixtures.go
  pkg/p2p/peer/processor.go
  pkg/p2p/wire/message/agreement.go
  pkg/p2p/wire/message/agreement_in_test.go
  pkg/p2p/wire/message/score.go
  pkg/util/ruskmock/server.go
Labels: team:WebTech, type:bug

#1095 Publish Reduction and Agreement messages in Kadcast
  cmd/dusk/server.go
  harness/engine/network.go
  harness/tests/localnet_test.go
  pkg/config/consts.go
  pkg/core/candidate/requestor.go
  pkg/core/consensus/agreement/agreement_test.go
  pkg/core/consensus/agreement/step.go
  pkg/core/consensus/comms.go
  pkg/core/consensus/reduction/firststep/step.go
  pkg/core/consensus/reduction/reduction.go
  pkg/core/consensus/reduction/secondstep/step.go
  pkg/core/consensus/selection/step.go
  pkg/core/consensus/testing/utils.go
  pkg/p2p/kadcast/writer.go
  pkg/p2p/peer/peer.go
  pkg/p2p/peer/processor.go
  pkg/p2p/wire/message/message.go
  pkg/util/nativeutils/eventbus/mock.go
Labels: team:WebTech
