Repository dusk-network/dusk-blockchain, pull requests merged in 2021-03, with the labels that each got.

#948 Introduce PeerID to all MessageProcessor handlers
  Makefile
  pkg/core/candidate/requestor.go
  pkg/core/candidate/requestor_test.go
  pkg/core/chain/chain.go
  pkg/core/chain/chain_rc_test.go
  pkg/core/chain/chain_test.go
  pkg/core/chain/synchronizer.go
  pkg/core/chain/synchronizer_test.go
  pkg/core/consensus/agreement/agreement_test.go
  pkg/core/consensus/publisher.go
  pkg/core/mempool/mempool.go
  pkg/core/mempool/mempool_test.go
  pkg/p2p/peer/peer.go
  pkg/p2p/peer/peer_test.go
  pkg/p2p/peer/processor.go
  pkg/p2p/peer/responding/blockhashbroker.go
  pkg/p2p/peer/responding/blockhashbroker_test.go
  pkg/p2p/peer/responding/candidatebroker.go
  pkg/p2p/peer/responding/candidatebroker_test.go
  pkg/p2p/peer/responding/databroker.go
  pkg/p2p/peer/responding/databroker_test.go
  pkg/p2p/peer/responding/datarequestor.go
  pkg/p2p/peer/responding/datarequestor_test.go
  pkg/p2p/peer/responding/ponger.go
Labels: area:p2p, team:WebTech

#967 Lock Chain mutex when sync timer expires
  pkg/core/chain/chain.go
  pkg/core/chain/synchronizer.go
  pkg/core/chain/synchronizer_test.go
Labels: team:WebTech, type:race

#965 Implement node.ConfigService
  cmd/dusk/server.go
  cmd/dusk/setconfig.go
  cmd/utils/grpcclient/client.go
  cmd/utils/grpcclient/configservice.go
  cmd/utils/main.go
  cmd/utils/tps.sh
  devnet.sh
  docs/elk.md
  go.mod
  pkg/core/mempool/mempool.go
Labels: team:WebTech

#962 Add comprehensive logging to the RUSK mock server
  cmd/utils/main.go
  harness/engine/network.go
  pkg/util/legacy/conversions.go
  pkg/util/ruskmock/server.go
Labels: team:WebTech, type:tech-debt

#970 Assign correct type id to Transfer Tx
  harness/engine/profiles.go
  pkg/util/legacy/conversions.go
  pkg/util/ruskmock/server.go
Labels: team:WebTech, type:bug

#972 Introduce TTL property to Cucko Filter instance per round
  cmd/dusk/server.go
  pkg/config/groups.go
  pkg/config/samples/default.dusk.toml
  pkg/core/consensus/testing/utils.go
  pkg/p2p/peer/dupemap/dupemap.go
  pkg/p2p/peer/dupemap/dupemap_test.go
  pkg/p2p/peer/dupemap/tmpmap.go
  pkg/p2p/peer/dupemap/tmpmap_test.go
  pkg/p2p/peer/processor.go
  pkg/p2p/peer/responding/datarequestor.go
  pkg/p2p/peer/responding/datarequestor_test.go
Labels: area:p2p, team:WebTech

#978 Add gas limit and gas price fields to tx queries
  go.sum
  pkg/core/data/ipc/transactions/transaction.go
  pkg/gql/README.md
  pkg/gql/query/transactions.go
  pkg/gql/query/transactions_test.go
  pkg/gql/query/types.go
Labels: area:tx, area:ui, team:WebTech, type:feature

#982 Remove usage of hardcoded tx hash in GQL block tests
  pkg/gql/query/blocks_test.go
Labels: area:testing, status:minor, team:WebTech, type:refactor

#986 Add BencmarkProcessTx tests
  pkg/core/data/ipc/transactions/fixtures.go
  pkg/core/mempool/mempool_test.go
Labels: team:WebTech

#988 Bump version to 0.4.1
  pkg/p2p/wire/protocol/protocol.go
Labels: team:WebTech

#989 Use wss endpoint on TLS enabled
  pkg/gql/README.md
  pkg/gql/httpserver.go
  pkg/gql/httpserver_test.go
Labels: team:WebTech

#991 Ensure highestSeen is updated when a block is received from consensus
  pkg/core/chain/chain.go
Labels: area:block-validation, team:WebTech, type:rfc

#993 Measure network TPS
  Makefile
  go.mod
  go.sum
  harness/engine/utils.go
  harness/tests/localnet_test.go
Labels: team:WebTech

#995 Remove GracefulClose call in utils methods
  harness/engine/utils.go
Labels: team:WebTech

#996 Add a utility which continually spams transactions from a node
  cmd/utils/main.go
  cmd/utils/tps/tps.go
Labels: area:testing, area:tx, team:WebTech, type:feature
