Repository dusk-network/dusk-blockchain, pull requests merged in 2021-04, with the labels that each got.

#1001 Increase block and p2p-based limits for transaction processing
  pkg/core/consensus/blockgenerator/candidate/blockgenerator.go
  pkg/p2p/wire/protocol/frame.go
Labels: area:p2p, area:tx, team:WebTech, type:rfc

#1007 Concurrently process transaction sends in the mempool
  pkg/core/mempool/mempool.go
  pkg/core/transactor/listener.go
Labels: area:testing, team:WebTech, type:bug

#1008 Alleviate bottleneck in removeAccepted
  go.sum
  pkg/core/mempool/hashmap.go
  pkg/core/mempool/interface.go
  pkg/core/mempool/mempool.go
Labels: area:testing, area:tx, team:WebTech, type:bug

#1013 Add the config name to the error message
  pkg/config/genesis/presets.go
Labels: area:monitoring, team:WebTech, type:rfc

#1015 Bump wallet version
  go.mod
  go.sum
Labels: team:WebTech

#1010 Introduce CPU profiling for Rusk Mock and transactor stats
  cmd/utils/main.go
  cmd/utils/mock/mock.go
  go.mod
  go.sum
  harness/engine/network.go
  harness/tests/localnet_test.go
  pkg/core/transactor/listener.go
Labels: team:WebTech

#1018 Enable unix transport for Rusk service
  cmd/dusk/server.go
  harness/engine/network.go
  harness/engine/node.go
  harness/engine/profiles.go
  harness/engine/utils.go
  harness/tests/localnet_test.go
  pkg/util/ruskmock/server.go
Labels: team:WebTech

#1022 Introduce Reserved field in Gossip structure
  pkg/p2p/wire.md
  pkg/p2p/wire/README.md
  pkg/p2p/wire/protocol/frame.go
  pkg/p2p/wire/protocol/frame_test.go
  pkg/p2p/wire/protocol/gossip.go
  pkg/p2p/wire/protocol/gossip_test.go
  pkg/p2p/wire/protocol/stats.go
Labels: team:WebTech

#1026 Add UNIX prefix to TPS util address in case we're using UNIX sockets
  cmd/utils/tps/tps.go
  pkg/core/mempool/mempool.go
Labels: area:deployment, area:testing, area:tx, team:WebTech, type:feature

#1027 Drop transactions if the mempool reaches max capacity
  pkg/core/mempool/mempool.go
Labels: area:tx, team:WebTech, type:rfc, type:vulnerability
