Repository dusk-network/dusk-blockchain, pull requests merged in 2021-02, with the labels that each got.

#887 Set a positive SessionDurationMins
  pkg/rpc/client/client_test.go
Labels: area:testing, team:WebTech

#885 Convert StandardType (3) to TransferType (0)
  harness/engine/utils.go
  harness/tests/localnet_test.go
  pkg/util/legacy/conversions.go
Labels: team:WebTech

#897 Reintroduce synchronicity between the Synchronizer, Chain and Consensus loop
  cmd/dusk/server.go
  pkg/core/chain/chain.go
  pkg/core/chain/chain_rc_test.go
  pkg/core/chain/chain_test.go
  pkg/core/chain/synchronizer.go
  pkg/core/chain/synchronizer_test.go
  pkg/core/consensus/agreement/agreement_test.go
  pkg/core/consensus/agreement/step.go
  pkg/core/loop/consensus.go
  pkg/core/loop/consensus_test.go
Labels: area:architecture, area:block-generation, area:block-validation, team:WebTech, type:rfc

#902 Support rusk.Wallet GetBalance grpc
  cmd/dusk/server.go
  go.mod
  go.sum
  harness/tests/localnet_test.go
  pkg/core/data/ipc/transactions/provider.go
  pkg/core/transactor/listener.go
  pkg/rpc/client/client.go
  pkg/util/ruskmock/server.go
Labels: team:WebTech

#905 Add a grace period for new stakes to become active
  go.mod
  go.sum
  pkg/core/chain/legacy.go
  pkg/util/ruskmock/server.go
Labels: area:block-validation, team:WebTech, type:rfc

#903 Move GetSyncProgress method back to the Chain
  cmd/wallet/conf/client.go
  cmd/wallet/prompt/prompt.go
  go.mod
  go.sum
  pkg/core/chain/chain.go
  pkg/core/chain/chain_test.go
  pkg/core/chain/synchronizer.go
  pkg/core/chain/synchronizer_test.go
Labels: area:IPC, area:ui, team:WebTech, type:refactor

#904 Restrict outgoing stake transactions if node is not synced
  cmd/dusk/server.go
  pkg/core/chain/chain.go
  pkg/core/chain/chain_test.go
  pkg/core/consensus/testing/node.go
  pkg/core/transactor/transactor.go
Labels: area:tx, team:WebTech, type:rfc, type:vulnerability

#907 Update README.md
  README.md
Labels: area:documentation, status:minor, team:WebTech, type:docs

#919 Remove outdated JSON-RPC API documentation
  pkg/rpc.md
Labels: area:documentation, team:WebTech

#918 Remove outdated pre-requisites folder
  docs/pre-requisites/1finitefield.md
  docs/pre-requisites/2ecc.md
  docs/pre-requisites/4stealthaddr.md
  docs/pre-requisites/5ringsig.md
  docs/pre-requisites/README.md
Labels: area:documentation, team:WebTech

#920 Add coding convention to fail as soon as possible
  CONTRIBUTING.md
Labels: area:documentation, team:WebTech

#921 Add workflow diagram which highlights block processing decision tree
  pkg/core/chain/chain.md
  pkg/core/chain/chain_processing_flow.jpg
Labels: area:documentation, team:WebTech

#922 Update wire protocol and peer architecture documentation
  pkg/p2p/README.md
  pkg/p2p/p2p_component_diagram.jpg
  pkg/p2p/wire.md
  pkg/p2p/wire/protocol/frame.go
Labels: area:documentation, area:p2p, team:WebTech

#923 Update verifiers documentation
  pkg/core/verifiers.md
  pkg/core/verifiers/README.md
  pkg/core/verifiers/block.go
Labels: area:documentation, team:WebTech

#930 Ensure deadlock can not happen in acceptConsensusResults
  pkg/core/chain/chain.go
Labels: team:WebTech, type:bug

#924 Improve Chain documentation
  pkg/core/chain/README.md
  pkg/core/chain/chain.go
  pkg/core/chain/chain.md
Labels: area:documentation, team:WebTech

#909 Secure `dupemap` against spam attacks
  cmd/dusk/server.go
  go.mod
  go.sum
  pkg/config/groups.go
  pkg/config/samples/default.dusk.toml
  pkg/p2p/kadcast/router.go
  pkg/p2p/kadcast/testing.go
  pkg/p2p/peer/dupemap/dupemap.go
  pkg/p2p/peer/dupemap/dupemap_test.go
  pkg/p2p/peer/dupemap/tmpmap.go
  pkg/p2p/peer/dupemap/tmpmap_test.go
  pkg/p2p/peer/factory.go
  pkg/p2p/peer/handshake_test.go
  pkg/p2p/peer/peer_in_test.go
  pkg/p2p/peer/peer_test.go
  pkg/p2p/peer/responding/databroker.go
  pkg/p2p/peer/responding/datarequestor.go
Labels: team:WebTech, type:vulnerability

#931 Update consensus package documentation
  pkg/core/consensus/README.md
  pkg/core/consensus/agreement/README.md
  pkg/core/consensus/agreement/agreement.md
  pkg/core/consensus/blockgenerator/README.md
  pkg/core/consensus/blockgenerator/candidate/readme.md
  pkg/core/consensus/blockgenerator/generation.md
  pkg/core/consensus/blockgenerator/score/README.md
  pkg/core/consensus/blockgenerator/score/README.md~master
  pkg/core/consensus/blockgenerator/score/score.md
  pkg/core/consensus/candidate/README.md
  pkg/core/consensus/candidate/candidate.md
  pkg/core/consensus/committee/README.md
  pkg/core/consensus/committee/committee.md
  pkg/core/consensus/consensus.md
  pkg/core/consensus/factory/README.md
  pkg/core/consensus/factory/factory.md
  pkg/core/consensus/reduction/README.md
  pkg/core/consensus/reduction/reduction.md
  pkg/core/consensus/selection/README.md
  pkg/core/consensus/selection/selection.md
  pkg/core/consensus/user/README.md
  pkg/core/loop/README.md
Labels: area:documentation, team:WebTech

#945 Implement outSyncTimer functionality in Synchronizer
  harness/engine/utils.go
  harness/tests/localnet_test.go
  pkg/core/chain/outsynctimer.go
  pkg/core/chain/outsynctimer_test.go
  pkg/core/chain/synchronizer.go
  pkg/p2p/peer/peer.go
Labels: team:WebTech, type:vulnerability
