Repository dusk-network/dusk-blockchain, pull requests merged in 2021-01, with the labels that each got.

#820 Change DUSK denomination from 8 to 10 decimals
  pkg/core/data/wallet/wallet.go
Labels: area:wallet, status:minor, type:refactor

#828 Store bid values when making bid transaction
  pkg/core/transactor/listener.go
Labels: area:block-generation, area:wallet, type:tech-debt

#842 Change 'trace message routing' log level to trace
  pkg/p2p/peer/peer.go
Labels: area:p2p, type:rfc

#844 Refine password entry flow
  cmd/dusk/server.go
Labels: area:ui, type:rfc, type:tech-debt

#824 Remove load menu from CLI wallet
  cmd/wallet/main.go
  cmd/wallet/prompt/loading.go
  cmd/wallet/prompt/prompt.go
Labels: area:IPC, area:wallet, type:rfc

#838 Clean up and document the rusk mock server, delete legacy genesis block
  cmd/dusk/server.go
  cmd/utils/main.go
  cmd/utils/mock/mock.go
  harness/data/wallet-9000.dat
  harness/data/wallet-9001.dat
  harness/data/wallet-9002.dat
  harness/data/wallet-9003.dat
  harness/data/wallet-9004.dat
  harness/data/wallet-9005.dat
  harness/data/wallet-9006.dat
  harness/data/wallet-9007.dat
  harness/data/wallet-9008.dat
  harness/data/wallet-9009.dat
  harness/data/wallet-9010.dat
  harness/engine/network.go
  harness/engine/node.go
  harness/engine/profiles.go
  pkg/config/consts.go
  pkg/config/groups.go
  pkg/config/loader.go
  pkg/core/chain/chain.go
  pkg/util/legacy/README.md
  pkg/util/legacy/conversions.go
  pkg/util/legacy/conversions_test.go
  pkg/util/legacy/genesis.go
  pkg/util/legacy/marshalling.go
  pkg/util/ruskmock/README.md
  pkg/util/ruskmock/config.go
  pkg/util/ruskmock/server.go
  pkg/util/ruskmock/server_test.go
Labels: area:IPC, area:testing, need:documentation, type:refactor

#850 Remove obsolete documentation, add contribution guidelines
  CONTRIBUTING.md
  docs/code-conventions.md
  docs/peer/block hash broker.png
  docs/peer/databroker.png
  docs/peer/datarequestor.png
  docs/peer/synchronizer.png
Labels: area:documentation

#861 Add succeeding block to sequencer, if block was discarded
  pkg/core/chain/chain.go
  pkg/core/chain/sequencer.go
  pkg/core/chain/synchronizer.go
  pkg/core/chain/synchronizer_test.go
Labels: area:block-validation, type:bug

#851 Add a document describing ZenHub workflow
  docs/internal/zenhub.md
Labels: area:documentation

#864 Use devnet-wallets in test-harness
  harness/data/wallet-9000.dat
  harness/data/wallet-9001.dat
  harness/data/wallet-9002.dat
  harness/data/wallet-9003.dat
  harness/data/wallet-9004.dat
  harness/data/wallet-9005.dat
  harness/data/wallet-9006.dat
  harness/data/wallet-9007.dat
  harness/data/wallet-9008.dat
  harness/data/wallet-9009.dat
  harness/data/wallet-9010.dat
  harness/engine/network.go
  harness/engine/profiles.go
Labels: area:testing

#871 Add step field to log entries for shouldProcess
  pkg/core/consensus/reduction/reduction.go
  pkg/core/consensus/selection/step.go
Labels: area:monitoring, status:minor, team:WebTech

#872 Implement handlers for both topics.MemPool and topics.Pong
  cmd/dusk/server.go
  pkg/core/mempool/mempool.go
  pkg/p2p/peer/responding/databroker.go
  pkg/p2p/peer/responding/databroker_test.go
  pkg/p2p/peer/responding/ponger.go
Labels: team:WebTech, type:bug

#870 Start consensus only after all nodes have been initialized
  pkg/core/consensus/testing/consensus_test.go
  pkg/core/consensus/testing/node.go
Labels: area:testing, team:WebTech, type:bug

#879 Close websockets connections when they are not in use
  pkg/gql/httpserver.go
  pkg/gql/httpserver_test.go
  pkg/gql/notifications/broker.go
  pkg/gql/notifications/client.go
  pkg/gql/notifications/pool.go
Labels: team:WebTech, type:bug

#883 Add lint for license headers
  .github/workflows/dusk_ci.yml
  Makefile
  go.mod
  go.sum
  mocks/Event.go
  mocks/EventHandler.go
  mocks/EventProcessor.go
  pkg/core/chain/chain_rc_test.go
  pkg/core/consensus/blockgenerator/candidate/devnet_genesis_test.go
  pkg/p2p/wire/encoding/integers.go
  pkg/p2p/wire/encoding/miscdata.go
  pkg/p2p/wire/encoding/vardata.go
  pkg/p2p/wire/encoding/varint.go
  pkg/util/legacy/conversions_test.go
  pkg/util/ruskmock/config.go
  pkg/util/ruskmock/server_test.go
  scripts/build.go
Labels: area:conf&build, area:documentation, team:WebTech

#877 Buffer sends on CatchBlockChan
  pkg/core/chain/chain.go
  pkg/core/chain/chain_test.go
  pkg/core/chain/synchronizer.go
  pkg/core/chain/synchronizer_test.go
Labels: team:WebTech, type:bug, type:rfc
