Repository dusk-network/dusk-blockchain, pull requests merged in 2021-07, with the labels that each got.

#1109 Discard duplicated votes from a single Provisioner
  pkg/core/consensus/reduction/aggregator.go
  pkg/core/consensus/testing/utils.go
  pkg/util/nativeutils/sortedset/sortedset.go
  pkg/util/nativeutils/sortedset/sortedset_test.go
Labels: team:WebTech

#1111 Improve consensus implementation traceability
  cmd/dusk/action.go
  harness/engine/profiles.go
  pkg/core/consensus/agreement/handler.go
  pkg/core/consensus/committee/handler.go
  pkg/core/consensus/reduction/aggregator.go
  pkg/core/consensus/reduction/firststep/step.go
  pkg/core/consensus/reduction/secondstep/step.go
  pkg/core/consensus/selection/step.go
  pkg/core/consensus/user/provisioners.go
  pkg/core/consensus/user/sortition.go
  pkg/p2p/wire/message/reduction.go
  pkg/util/nativeutils/sortedset/cluster.go
  pkg/util/nativeutils/sortedset/sortedset.go
  pkg/util/ruskmock/server.go
  pkg/util/stringify.go
Labels: area:monitoring, team:WebTech

#1119 Rename Score message to NewBlock message
  Makefile
  cmd/dusk/server.go
  pkg/core/consensus/blockgenerator/candidate/blockgenerator.go
  pkg/core/consensus/blockgenerator/candidate/mock.go
  pkg/core/consensus/fixtures.go
  pkg/core/consensus/reduction/firststep/reduction_test.go
  pkg/core/consensus/reduction/firststep/step.go
  pkg/core/consensus/selection/handler.go
  pkg/core/consensus/selection/selector_test.go
  pkg/core/consensus/selection/step.go
  pkg/core/consensus/selection/testutil.go
  pkg/core/loop/consensus.go
  pkg/p2p/kadcast/writer.go
  pkg/p2p/peer/processor.go
  pkg/p2p/peer/registry.go
  pkg/p2p/wire.md
  pkg/p2p/wire/message/message.go
  pkg/p2p/wire/message/newblock.go
  pkg/p2p/wire/message/newblock_test.go
  pkg/p2p/wire/topics/topics.go
Labels: team:WebTech

#1120 Limit max amount of messages in consensus queue
  pkg/core/consensus/agreement/step.go
  pkg/core/consensus/queue.go
  pkg/core/consensus/queue_test.go
  pkg/core/consensus/reduction/reduction.go
  pkg/core/consensus/selection/step.go
Labels: team:WebTech, type:rfc, type:vulnerability

#1121 Replace dusk-wallet tx model for a mocked one
  pkg/core/data/ipc/transactions/payload.go
  pkg/gql/query/transactions_test.go
  pkg/util/legacy/README.md
  pkg/util/legacy/conversions.go
  pkg/util/legacy/conversions_test.go
  pkg/util/ruskmock/server.go
  pkg/util/ruskmock/server_test.go
Labels: area:tx, team:WebTech, type:refactor

#1123 Change quorum from 3/4ths to 2/3rds
  pkg/core/consensus/agreement/agreement_in_test.go
  pkg/core/consensus/agreement/handler.go
  pkg/core/consensus/reduction/handler.go
  pkg/p2p/wire/message/reduction.go
Labels: area:block-validation, team:WebTech, type:refactor

#1125 Prevent putting a transaction in the mempool twice
  pkg/core/mempool/hashmap.go
Labels: area:block-generation, area:tx, team:WebTech, type:bug

#1128 Extend default dupemap timeout to 60s
  pkg/p2p/peer/dupemap/dupemap.go
Labels: area:p2p, team:WebTech, type:rfc

#1126 Add retry procedure for contacting voucher
  cmd/dusk/server.go
Labels: area:p2p, team:WebTech

#1134 Update expiryTime of topics.Inv dupemap
  pkg/p2p/peer/dupemap/dupemap.go
  pkg/p2p/peer/processor.go
  pkg/p2p/peer/responding/datarequestor.go
Labels: team:WebTech

#1133 Implement a persistent storage for ruskmock
  go.mod
  go.sum
  pkg/rpc/server/setup.go
  pkg/util/ruskmock/db.go
  pkg/util/ruskmock/server.go
Labels: team:WebTech
