Repository dusk-network/dusk-blockchain, pull requests merged in 2022-01, with the labels that each got.

#1236 Enable test-harness running rusk with unix domain socket IPC
  harness/engine/network.go
  harness/engine/profiles.go
  harness/tests/localnet_test.go
  pkg/p2p/kadcast/peer.go
Labels: mark:testnet

#1235 Disallow ChanListeners to report warnings on a suspended consensus
  pkg/core/loop/consensus.go
  pkg/util/nativeutils/eventbus/listener.go
  pkg/util/nativeutils/eventbus/publisher.go
Labels: team:WebTech, mark:testnet

#1238 Support both rate limiter and pendingPropagation in mempool
  harness/engine/profiles.go
  harness/engine/utils.go
  harness/tests/localnet_test.go
  pkg/config/groups.go
  pkg/config/samples/default.dusk.toml
  pkg/core/mempool/mempool.go
Labels: mark:testnet

#1244 Allow to launch testbed on a remote cluster
  pkg/p2p/testbed/cluster_test.go
  pkg/p2p/testbed/kadcast_test.go
Labels: area:testing, mark:testnet

#1245 Terminate gracefully all subsystems/components and pending grpc requests
  cmd/dusk/server.go
  pkg/core/mempool/mempool.go
  pkg/gql/httpserver.go
  pkg/gql/httpserver_test.go
  pkg/p2p/kadcast/peer.go
  pkg/p2p/kadcast/reader.go
  pkg/util/nativeutils/eventbus/eventbus.go
  pkg/util/nativeutils/eventbus/listener.go
  pkg/util/nativeutils/eventbus/listenermap.go
Labels: mark:testnet

#1248 Remote testbed verify truncated message
  pkg/p2p/testbed/cluster_test.go
  pkg/p2p/testbed/kadcast_test.go
Labels: area:testing, mark:testnet

#1242 Reintroduce priority mapper in topics.Kadcast Collector
  pkg/p2p/kadcast/writer.go
Labels: mark:testnet

#1254 Reintroduce kadcast test harness
  .github/workflows/dusk_ci.yml
  Makefile
Labels: mark:testnet

#1251 Initial implementation of BuntDB backend for Mempool
  cmd/dusk/server.go
  harness/engine/profiles.go
  pkg/config/groups.go
  pkg/config/samples/default.dusk.toml
  pkg/core/chain/chain.go
  pkg/core/mempool/buntdb.go
  pkg/core/mempool/buntdb_test.go
  pkg/core/mempool/hashmap.go
  pkg/core/mempool/hashmap_test.go
  pkg/core/mempool/interface.go
  pkg/core/mempool/mempool.go
  pkg/core/mempool/mempool_test.go
  pkg/util/ruskmock/db.go
Labels: mark:testnet

#1267 Update dusk-blockchain and rusk mock with Rusk Schema most recent changes
  go.mod
  go.sum
  pkg/core/chain/chain.go
  pkg/core/data/ipc/transactions/fixtures.go
  pkg/core/data/ipc/transactions/provider.go
  pkg/p2p/kadcast/peer_test.go
  pkg/util/ruskmock/server.go
  pkg/util/ruskmock/server_test.go
Labels: mark:testnet

#1271 Decrement kadcast height value on message receiving
  pkg/core/mempool/mempool.go
  pkg/p2p/kadcast/reader.go
  pkg/p2p/kadcast/writer.go
Labels: mark:testnet

#1268 Update bls cgo library to latest version
  go.mod
  go.sum
Labels: mark:testnet

#1278 Change the encryption schema for the consensus wallet
  go.mod
  go.sum
  pkg/core/consensus/key/keys.go
  pkg/core/consensus/key/keys_test.go
Labels: mark:testnet
